Feature/custom message
FancyMcPlugins/FancyNpcs pull request #16
Opened 2023-05-19 19:33 UTC by Zemux1613

#15

2023-05-19 20:00 UTC, OliverSchlueter commented
I think your branch was outdated

2023-05-19 20:51 UTC, Zemux1613 commented
now

2023-05-20 14:48 UTC, OliverSchlueter requested changes

2023-05-20 14:48 UTC, OliverSchlueter commented on src/main/java/de/oliver/fancynpcs/utils/EntityTypes.java
> +                ex.printStackTrace();
The `ex.printStackTrace();` needs to be removed, it spams the console

2023-05-20 14:48 UTC, OliverSchlueter commented on src/main/java/de/oliver/fancynpcs/commands/NpcCMD.java
> +                if (args.length >= 3) {
What if the message is longer than one word?

2023-05-20 14:48 UTC, OliverSchlueter commented on src/main/java/de/oliver/fancynpcs/commands/NpcCMD.java
> +                    npc.setOnClick(player -> player.sendMessage(Component.text(message.toString())));
This should be in Npc#updateMessage

2023-05-21 16:14 UTC, OliverSchlueter approved these changes

2023-05-21 16:17 UTC, merged