Fix right click not working on non player npcs
FancyMcPlugins/FancyNpcs pull request #91
Opened 2024-02-24 19:50 UTC by alexcastro1919

As the title says, now non player npcs support right click.

2024-02-25 16:36 UTC, OliverSchlueter commented
Could you describe under which conditions right clicking non player npcs is not working?
I've tried a few types and it worked for me.

2024-02-25 17:38 UTC, alexcastro1919 commented
I tried with CHEST_BOAT and WANDERING_TRADER and none worked

2024-02-25 17:43 UTC, alexcastro1919 commented
This was the condition causing the issue
`if (!event.isAttack() && (event.getHand() == EquipmentSlot.HAND || event.getClickedRelativePosition() != null))`
I suppose it was because getClickedRelativePosition returned not null (and obviously right click is not an attack).

2024-02-25 18:03 UTC, OliverSchlueter requested changes

2024-02-25 18:03 UTC, OliverSchlueter commented on src/main/java/de/oliver/fancynpcs/listeners/PlayerUseUnknownEntityListener.java
> +        /* This is not needed
You can actually remove this, if it's not needed.

2024-02-25 18:16 UTC, alexcastro1919 reviewed
Removed

2024-02-25 18:17 UTC, OliverSchlueter approved these changes

2024-02-25 18:17 UTC, merged

2024-02-25 18:17 UTC, OliverSchlueter commented
Thank you!

2024-03-05 17:05 UTC, OliverSchlueter commented
Not working on Folia
![image](https://github.com/FancyMcPlugins/FancyNpcs/assets/79666085/30e73cce-c2df-4385-a1dd-93e1bc52aca2)

I reverted the commit for now, will need to investigate the actual problem